# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
    default: arbitrum-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
    - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0
    - Badger-Finance/badger-vaults-1.5@0.1.1
    - Uniswap/v3-core@1.0.0

# path remapping to support imports from GitHub/NPM
compiler:
    solc:
        version: 0.6.12
        remappings:
            - "@openzeppelin-contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0/contracts/"
            - "@badger-finance=Badger-Finance/badger-vaults-1.5@0.1.1/contracts/"
            - "@uniswap=Uniswap/v3-core@1.0.0/contracts/"

reports:
    exclude_contracts:
        - SafeMath
